<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->delete();

        DB::table('products')->insert(array (
            0 =>
            array (
                'id' => 1,
                'code' => 'P001',
                'name' => 'CHATARRA MIXTA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 11,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-07 15:54:13',
                'updated_at' => '2023-12-12 16:07:24'
                ),
            1 =>
            array (
                'id' => 2,
                'code' => 'P002',
                'name' => 'COBRE MIXTO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 11,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-07 16:49:59',
                'updated_at' => '2023-12-12 16:07:38'
                ),
            2 =>
            array (
                'id' => 3,
                'code' => 'P003',
                'name' => 'CABLE DE COBRE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 11,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:08:43',
                'updated_at' => '2023-12-12 16:08:43'
                ),
            3 =>
            array (
                'id' => 4,
                'code' => 'P004',
                'name' => 'RADIADOR DE COBRE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 12,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:10:19',
                'updated_at' => '2023-12-12 16:10:19'
                ),
            4 =>
            array (
                'id' => 5,
                'code' => 'P005',
                'name' => 'RADIADOR MIXTO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 12,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:11:21',
                'updated_at' => '2023-12-12 16:11:21'
                ),
            5 =>
            array (
                'id' => 6,
                'code' => 'P006',
                'name' => 'RADIADOR ALUMINIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 12,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:12:45',
                'updated_at' => '2023-12-12 16:12:45'
                ),
            6 =>
            array (
                'id' => 7,
                'code' => 'P007',
                'name' => 'ALUMINIO GRUESO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:14:22',
                'updated_at' => '2023-12-12 16:14:22'
                ),
            7 =>
            array (
                'id' => 8,
                'code' => 'P008',
                'name' => 'ALUMINIO BLANDO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:15:17',
                'updated_at' => '2023-12-12 16:15:17'
                ),
            8 =>
            array (
                'id' => 9,
                'code' => 'P009',
                'name' => 'ALUMINIO POTE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:16:10',
                'updated_at' => '2023-12-12 16:16:10'
                ),
            9 =>
            array (
                'id' => 10,
                'code' => 'P010',
                'name' => 'ALUMINIO PERFIL LIMPIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:17:16',
                'updated_at' => '2023-12-12 16:17:16'
                ),
            10 =>
            array (
                'id' => 11,
                'code' => 'P011',
                'name' => 'ALUMINIO OLLA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:18:01',
                'updated_at' => '2023-12-12 16:18:01'
                ),
            11 =>
            array (
                'id' => 12,
                'code' => 'P012',
                'name' => 'ALUMINIO REVUELTO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:20:42',
                'updated_at' => '2023-12-12 16:20:42'
                ),
            12 =>
            array (
                'id' => 13,
                'code' => 'P013',
                'name' => 'ALUMINIO CONTAMINADO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:21:30',
                'updated_at' => '2023-12-12 16:21:30'
                ),
            13 =>
            array (
                'id' => 14,
                'code' => 'P014',
                'name' => 'ALUMINIO PERSIANA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:22:55',
                'updated_at' => '2023-12-12 16:22:55'
                ),
            14 =>
            array (
                'id' => 15,
                'code' => 'P015',
                'name' => 'ALUMINIO PERFIL LIMPIEZA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:23:43',
                'updated_at' => '2023-12-12 16:23:43'
                ),
            15 =>
            array (
                'id' => 16,
                'code' => 'P016',
                'name' => 'GUAYA DE ALUMINIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:24:51',
                'updated_at' => '2023-12-12 16:24:51'
                ),
            16 =>
            array (
                'id' => 17,
                'code' => 'P017',
                'name' => 'LITOGRAFIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:25:38',
                'updated_at' => '2023-12-12 16:25:38'
                ),
            17 =>
            array (
                'id' => 18,
                'code' => 'P018',
                'name' => 'SALCHICHA LIMPIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 21,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:26:48',
                'updated_at' => '2023-12-12 16:27:54'
                ),
            18 =>
            array (
                'id' => 19,
                'code' => 'P019',
                'name' => 'SALCHUCHA SUCIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 21,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:27:30',
                'updated_at' => '2023-12-12 16:27:30'
                ),
            19 =>
            array (
                'id' => 20,
                'code' => 'P020',
                'name' => 'PLOMO LIMPIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 18,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:29:24',
                'updated_at' => '2023-12-12 16:29:24'
                ),
            20 =>
            array (
                'id' => 21,
                'code' => 'P021',
                'name' => 'PLOMO BALACIN',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 18,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:30:05',
                'updated_at' => '2023-12-12 16:30:05'
                ),
            21 =>
            array (
                'id' => 22,
                'code' => 'P022',
                'name' => 'SCRAT',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 18,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:30:51',
                'updated_at' => '2023-12-12 16:30:51'
                ),
            22 =>
            array (
                'id' => 23,
                'code' => 'P023',
                'name' => 'CANASTA LLENA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 4,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:31:40',
                'updated_at' => '2023-12-12 16:31:40'
                ),
            23 =>
            array (
                'id' => 24,
                'code' => 'P024',
                'name' => 'CANASTA VACIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 4,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:32:14',
                'updated_at' => '2023-12-12 16:32:14'
                ),
            24 =>
            array (
                'id' => 25,
                'code' => 'P025',
                'name' => 'CANASTA NEGRA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 4,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:32:50',
                'updated_at' => '2023-12-12 16:32:50'
                ),
            25 =>
            array (
                'id' => 26,
                'code' => 'P026',
                'name' => 'ARCHIVO LIMPIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 6,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:34:06',
                'updated_at' => '2023-12-12 16:34:06'
                ),
            26 =>
            array (
                'id' => 27,
                'code' => 'P027',
                'name' => 'ARCHIVO DE SELECCION',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 6,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:34:46',
                'updated_at' => '2023-12-12 16:34:46'
                ),
            27 =>
            array (
                'id' => 28,
                'code' => 'P028',
                'name' => 'PLEGA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 7,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:36:07',
                'updated_at' => '2023-12-12 16:36:54'
                ),
            28 =>
            array (
                'id' => 29,
                'code' => 'P029',
                'name' => 'VIRUTA DE BRONCE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:37:59',
                'updated_at' => '2023-12-12 16:37:59'
                ),
            29 =>
            array (
                'id' => 30,
                'code' => 'P030',
                'name' => 'VIRUTA DE HIERRO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:38:42',
                'updated_at' => '2023-12-12 16:38:42'
                ),
            30 =>
            array (
                'id' => 31,
                'code' => 'P031',
                'name' => 'VIRUTA DE ALUMINIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:44:50',
                'updated_at' => '2023-12-12 16:44:50'
                ),
            67 =>
            array (
                'id' => 32,
                'code' => 'P032',
                'name' => 'VIRUTA DE ACERO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:14:08',
                'updated_at' => '2023-12-12 17:14:08'
            )	,
            31 =>
            array (
                'id' => 33,
                'code' => 'P033',
                'name' => 'BAT N°40/36',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:46:42',
                'updated_at' => '2023-12-12 16:46:42'
                ),
            32 =>
            array (
                'id' => 34,
                'code' => 'P034',
                'name' => 'BAT N°42',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:47:18',
                'updated_at' => '2023-12-12 16:47:18'
                ),
            33 =>
            array (
                'id' => 35,
                'code' => 'P035',
                'name' => 'BAT N°48',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:48:05',
                'updated_at' => '2023-12-12 16:48:05'
                ),
            34 =>
            array (
                'id' => 36,
                'code' => 'P036',
                'name' => 'BAT N°27',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:48:40',
                'updated_at' => '2023-12-12 16:48:40'
                ),
            35 =>
            array (
                'id' => 37,
                'code' => 'P037',
                'name' => 'BAT N°30H',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:49:50',
                'updated_at' => '2023-12-12 16:49:50'
                ),
            36 =>
            array (
                'id' => 38,
                'code' => 'P038',
                'name' => 'BAT N°4D',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:50:36',
                'updated_at' => '2023-12-12 16:50:36'
                ),
            37 =>
            array (
                'id' => 39,
                'code' => 'P039',
                'name' => 'BAT N°8D',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:51:12',
                'updated_at' => '2023-12-12 16:51:12'
                ),
            38 =>
            array (
                'id' => 40,
                'code' => 'P040',
                'name' => 'BAT MOTO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:51:48',
                'updated_at' => '2023-12-12 16:51:48'
                ),
            39 =>
            array (
                'id' => 41,
                'code' => 'P041',
                'name' => 'BAT ESTACIONARIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:52:41',
                'updated_at' => '2023-12-12 16:52:41'
                ),
            40 =>
            array (
                'id' => 42,
                'code' => 'P042',
                'name' => 'PASTA GRUESA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:53:25',
                'updated_at' => '2023-12-12 16:53:25'
                ),
            41 =>
            array (
                'id' => 43,
                'code' => 'P043',
                'name' => 'PASTA SOPLADA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:54:00',
                'updated_at' => '2023-12-12 16:54:00'
                ),
            42 =>
            array (
                'id' => 44,
                'code' => 'P044',
                'name' => 'PASTA REVUELTA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:54:40',
                'updated_at' => '2023-12-12 16:54:40'
                ),
            43 =>
            array (
                'id' => 45,
                'code' => 'P045',
                'name' => 'PASTA NEGRA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:55:18',
                'updated_at' => '2023-12-12 16:55:18'
                ),
            44 =>
            array (
                'id' => 46,
                'code' => 'P046',
                'name' => 'PASTA ACRILICA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:56:07',
                'updated_at' => '2023-12-12 16:56:07'
                ),
            45 =>
            array (
                'id' => 47,
                'code' => 'P047',
                'name' => 'PET TRASPARENTE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:57:06',
                'updated_at' => '2023-12-12 16:57:06'
                ),
            46 =>
            array (
                'id' => 48,
                'code' => 'P048',
                'name' => 'PET VERDE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:57:50',
                'updated_at' => '2023-12-12 16:57:50'
                ),
            47 =>
            array (
                'id' => 49,
                'code' => 'P049',
                'name' => 'COLOR AMBAR PONY',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:58:31',
                'updated_at' => '2023-12-12 16:58:31'
                ),
            48 =>
            array (
                'id' => 50,
                'code' => 'P050',
                'name' => 'PET DE ACEITE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:59:13',
                'updated_at' => '2023-12-12 16:59:13'
                ),
            49 =>
            array (
                'id' => 51,
                'code' => 'P051',
                'name' => 'PVC',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 16:59:48',
                'updated_at' => '2023-12-12 16:59:48'
                ),
            50 =>
            array (
                'id' => 52,
                'code' => 'P052',
                'name' => 'MANGUERA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 24,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:00:44',
                'updated_at' => '2023-12-12 17:00:44'
                ),
            51 =>
            array (
                'id' => 53,
                'code' => 'P053',
                'name' => 'ENVASE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 8,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:01:24',
                'updated_at' => '2023-12-12 17:01:24'
                ),
            52 =>
            array (
                'id' => 54,
                'code' => 'P054',
                'name' => 'PERIODICO LIMPIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 9,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:02:16',
                'updated_at' => '2023-12-12 17:02:16'
                ),
            53 =>
            array (
                'id' => 55,
                'code' => 'P055',
                'name' => 'PERIODICO ARRUGADO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 9,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:02:57',
                'updated_at' => '2023-12-12 17:02:57'
                ),
            54 =>
            array (
                'id' => 56,
                'code' => 'P056',
                'name' => 'ACERO LIMPIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 17,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:03:52',
                'updated_at' => '2023-12-12 17:03:52'
                ),
            55 =>
            array (
                'id' => 57,
                'code' => 'P057',
                'name' => 'ACERO CONTAMINADO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 17,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:04:31',
                'updated_at' => '2023-12-12 17:04:31'
                ),
            56 =>
            array (
                'id' => 58,
                'code' => 'P058',
                'name' => 'ENTEROS',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 26,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:05:34',
                'updated_at' => '2023-12-12 17:05:34'
                ),
            57 =>
            array (
                'id' => 59,
                'code' => 'P059',
                'name' => 'TECLAS',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 26,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:06:14',
                'updated_at' => '2023-12-12 17:06:14'
                ),
            58 =>
            array (
                'id' => 60,
                'code' => 'P060',
                'name' => 'RIN DE CARRO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 29,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:07:07',
                'updated_at' => '2023-12-12 17:07:07'
                ),
            59 =>
            array (
                'id' => 61,
                'code' => 'P061',
                'name' => 'RIN DE BICICLETA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 29,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:07:42',
                'updated_at' => '2023-12-12 17:07:42'
                ),
            60 =>
            array (
                'id' => 62,
                'code' => 'P062',
                'name' => 'UNIDAD PIPO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 30,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:08:36',
                'updated_at' => '2023-12-12 17:08:36'
                ),
            61 =>
            array (
                'id' => 63,
                'code' => 'P063',
                'name' => 'UNIDAD NORMAL',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 30,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:09:12',
                'updated_at' => '2023-12-12 17:09:12'
                ),
            62 =>
            array (
                'id' => 64,
                'code' => 'P064',
                'name' => 'UNIDAD GRANDE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 30,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:09:49',
                'updated_at' => '2023-12-12 17:09:49'
                ),
            63 =>
            array (
                'id' => 65,
                'code' => 'P065',
                'name' => 'VARILLA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:10:31',
                'updated_at' => '2023-12-12 17:10:31'
                ),
            64 =>
            array (
                'id' => 66,
                'code' => 'P066',
                'name' => 'ANGULO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:11:05',
                'updated_at' => '2023-12-12 17:11:05'
                ),
            65 =>
            array (
                'id' => 67,
                'code' => 'P067',
                'name' => 'TUBO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:11:36',
                'updated_at' => '2023-12-12 17:11:36'
                ),
            66 =>
            array (
                'id' => 68,
                'code' => 'P068',
                'name' => 'PLATINA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => 'noimage.jpg',
                'image' => '/storage/images/products/noimage.jpg',
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => '2023-12-12 17:12:10',
                'updated_at' => '2023-12-12 17:12:10'
                ),

        ));
    }
}
